server:
  port: 18088
  servlet:
    context-path: /shanhai
shanhai:
  log:
    consoleShow: true
    ignore-request-params:
      - cn.hutool.system.UserInfo
    req-json-pretty-format: true
    resp-json-pretty-format: true